spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: witsb_dba
    password: admin
    url: jdbc:postgresql://localhost:7432/witsb_db
logging:
  level:
    be.mathiasbosman.witsb: trace
witsb:
  fs:
    minio-url: http://localhost:19000/
    minio-key: minio
    minio-secret: minio123
    minio-bucket: witsbbucket
